/* eslint-disable */
// tslint:disable
/**
 * Appraisal Service
 * Appraisal Service
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import relevantData from './api/relevantData'
import * as t from './types'

export default function(app: Express, impl: t.ApiImplementation) {
	relevantData(app, impl.relevantData)
}
