/* eslint-disable */
// tslint:disable
/**
 * Appraisal Service
 * Appraisal Service
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

export namespace Api {
	export interface MessageData {
		message: string;
	}

	export interface RelevantDataDto {
		siNo?: string;
		details?: string;
	}

	export interface RelevantDataPagedResultData {
		/**
		 * @type {number}
		 * @memberof RelevantDataPagedResultData
		 */
		totalCount?: number;
		items?: Api.RelevantDataDto[];
	}

}
