openapi: 3.0.1
info:
  title: ConsultancyWorks Service
  description: ConsultancyWorks Service
  version: v1
servers:
  - url: http://localhost:5001
    description: Local Dev Server
paths:
  /ConsultancyWorks/getAll:
    get:
      tags:
        - consultancyworks
      parameters:
        - $ref: "#/components/parameters/limitParam"
        - $ref: "#/components/parameters/directionParam"
        - $ref: "#/components/parameters/sortByFieldParam"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsultancyWorksResultDto"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/ResourceNotFoundError"
  /ConsultancyWorks/get:
    get:
      tags:
        - consultancyworks
      parameters:
        - $ref: "#/components/parameters/siNo"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsultancyWorksDto"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/ResourceNotFoundError"
        "422":
          $ref: "#/components/responses/UnAcceptableInputs"
  /ConsultancyWorks/create:
    post:
      tags:
        - consultancyworks
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConsultancyWorksDto"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsultancyWorksDto"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/ResourceNotFoundError"
        "422":
          $ref: "#/components/responses/UnAcceptableInputs"
  /ConsultancyWorks/update:
    put:
      tags:
        - consultancyworks
      parameters:
        - $ref: "#/components/parameters/siNo"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConsultancyWorksDto"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConsultancyWorksDto"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/ResourceNotFoundError"
        "422":
          $ref: "#/components/responses/UnAcceptableInputs"
  /ConsultancyWorks/delete:
    delete:
      tags:
        - consultancyworks
      parameters:
        - $ref: "#/components/parameters/siNo"
      responses:
        "200":
          $ref: "#/components/responses/Success"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/ResourceNotFoundError"
        "422":
          $ref: "#/components/responses/UnAcceptableInputs"
components:
  parameters:
    siNo:
        name: siNo
        in: query
        description: siNo
        required: true
        schema:
          type: string
    limitParam:
      name: Limit
      in: query
      schema:
        type: integer
        nullable: true
    directionParam:
      name: Direction
      in: query
      schema:
        type: string
        enum:
          - asc
          - desc
        default: asc
    sortByFieldParam:
      name: SortByField
      in: query
      schema:
        type: string
        nullable: true
  responses:
    Success:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageDto"
    ResourceNotFoundError:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageDto"
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageDto"
    UnAcceptableInputs:
      description: Invalid Inputs
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageDto"
  schemas:
    MessageDto:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    ConsultancyWorksResultDto:
      type: object
      properties:
        totalCount:
          type: integer
        items:
          type: array
          items:
            $ref: "#/components/schemas/ConsultancyWorksDto"
    ConsultancyWorksDto:
      type: object
      properties:
        siNo:
          type: string
        facultyname:
          type: string
        tittle:
          type: string
        agency:
          type: string
        period:
          type: string
        amountMobilized:
          type: string
        apiScore:
          type: string