/* eslint-disable */
// tslint:disable
/**
 * service
 * service
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import * as extraactivities from './api/extraactivities/types'

export interface ApiImplementation {
	extraactivities: extraactivities.ExtraactivitiesApi
}
