/* eslint-disable */
// tslint:disable
/**
 * Appraisal Service
 * Appraisal Service
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import passport from 'passport'
import * as t from './types'
import * as v from '../../validation'
import { Api } from '../../models'

export default function(app: Express, impl: t.RelevantDataApi) {
	app.post(
		'/relevantData/create',
		function (req, res) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiRelevantDataDtoFromJson('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.postRelevantDataCreate(__body()).then(function (response) {
					if (response.status === 201) {
						let body: any
						try {
							body = v.modelApiRelevantDataDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.postRelevantDataCreate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(201)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.postRelevantDataCreate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.postRelevantDataCreate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 422) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.postRelevantDataCreate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(422)
						res.send(body)
						return
					}

					console.log('Unsupported response in relevantData.postRelevantDataCreate', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in relevantData.postRelevantDataCreate', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.delete(
		'/relevantData/delete',
		function (req, res) {
			try {
				impl.deleteRelevantDataDelete(v.parseString('query.Id', req.query['Id'])).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.deleteRelevantDataDelete', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.deleteRelevantDataDelete', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.deleteRelevantDataDelete', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 422) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.deleteRelevantDataDelete', error)
							res.status(500)
							res.send()
							return
						}

						res.status(422)
						res.send(body)
						return
					}

					console.log('Unsupported response in relevantData.deleteRelevantDataDelete', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in relevantData.deleteRelevantDataDelete', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.get(
		'/relevantData/get',
		function (req, res) {
			try {
				impl.getRelevantDataGet(v.parseString('query.Id', req.query['Id'])).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiRelevantDataDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.getRelevantDataGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.getRelevantDataGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.getRelevantDataGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 422) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.getRelevantDataGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(422)
						res.send(body)
						return
					}

					console.log('Unsupported response in relevantData.getRelevantDataGet', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in relevantData.getRelevantDataGet', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.get(
		'/relevantData/getAll',
		function (req, res) {
			try {
				impl.getRelevantDataGetAll().then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiRelevantDataPagedResultDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.getRelevantDataGetAll', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.getRelevantDataGetAll', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.getRelevantDataGetAll', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}

					console.log('Unsupported response in relevantData.getRelevantDataGetAll', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in relevantData.getRelevantDataGetAll', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.put(
		'/relevantData/update',
		function (req, res) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiRelevantDataDtoFromJson('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.putRelevantDataUpdate(v.parseString('query.Id', req.query['Id']), __body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiRelevantDataDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.putRelevantDataUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.putRelevantDataUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.putRelevantDataUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 422) {
						let body: any
						try {
							body = v.modelApiMessageDataToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in relevantData.putRelevantDataUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(422)
						res.send(body)
						return
					}

					console.log('Unsupported response in relevantData.putRelevantDataUpdate', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in relevantData.putRelevantDataUpdate', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

}
