/* eslint-disable */
// tslint:disable
/**
 * service
 * service
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

export namespace Api {
	export interface CoactivitiesDto {
		SINO?: string;
		Activity?: string;
		/**
		 * @type {number}
		 * @memberof CoactivitiesDto
		 */
		APIscore?: number;
	}

	export interface CoactivitiesPagedResultDto {
		/**
		 * @type {number}
		 * @memberof CoactivitiesPagedResultDto
		 */
		totalCount?: number;
		items?: Api.CoactivitiesDto[];
	}

	export enum DirectionParamEnum {
		Asc = 'asc',
		Desc = 'desc'
	}

	export interface MessageDto {
		message: string;
	}

}
