/* eslint-disable */
// tslint:disable
/**
 * service
 * service
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import passport from 'passport'
import * as t from './types'
import * as v from '../../validation'
import { Api } from '../../models'

export default function(app: Express, impl: t.ExtraactivitiesApi) {
	app.post(
		'/extraactivities/create',
		function (req, res) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiExtraactivitiesDtoFromJson('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.postExtraactivitiesCreate(__body()).then(function (response) {
					if (response.status === 201) {
						let body: any
						try {
							body = v.modelApiExtraactivitiesDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.postExtraactivitiesCreate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(201)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.postExtraactivitiesCreate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.postExtraactivitiesCreate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 422) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.postExtraactivitiesCreate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(422)
						res.send(body)
						return
					}

					console.log('Unsupported response in extraactivities.postExtraactivitiesCreate', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in extraactivities.postExtraactivitiesCreate', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.delete(
		'/extraactivities/delete',
		function (req, res) {
			try {
				impl.deleteExtraactivitiesDelete(v.parseString('query.Id', req.query['Id'])).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.deleteExtraactivitiesDelete', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.deleteExtraactivitiesDelete', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.deleteExtraactivitiesDelete', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 422) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.deleteExtraactivitiesDelete', error)
							res.status(500)
							res.send()
							return
						}

						res.status(422)
						res.send(body)
						return
					}

					console.log('Unsupported response in extraactivities.deleteExtraactivitiesDelete', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in extraactivities.deleteExtraactivitiesDelete', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.get(
		'/extraactivities/get',
		function (req, res) {
			try {
				impl.getExtraactivitiesGet(v.parseString('query.Id', req.query['Id'])).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiExtraactivitiesDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.getExtraactivitiesGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.getExtraactivitiesGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.getExtraactivitiesGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 422) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.getExtraactivitiesGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(422)
						res.send(body)
						return
					}

					console.log('Unsupported response in extraactivities.getExtraactivitiesGet', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in extraactivities.getExtraactivitiesGet', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.get(
		'/extraactivities/getAll',
		function (req, res) {
			try {
				impl.getExtraactivitiesGetAll(v.allowUndefined(v.parseInteger)('query.Limit', req.query['Limit']), v.allowUndefined(v.enumApiDirectionParamEnumFromJson)('query.Direction', req.query['Direction']), v.allowUndefined(v.parseString)('query.SortByField', req.query['SortByField'])).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiExtraactivitiesPagedResultDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.getExtraactivitiesGetAll', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.getExtraactivitiesGetAll', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.getExtraactivitiesGetAll', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}

					console.log('Unsupported response in extraactivities.getExtraactivitiesGetAll', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in extraactivities.getExtraactivitiesGetAll', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

	app.put(
		'/extraactivities/update',
		function (req, res) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiExtraactivitiesDtoFromJson('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.putExtraactivitiesUpdate(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiExtraactivitiesDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.putExtraactivitiesUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.send(body)
						return
					}
					if (response.status === 401) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.putExtraactivitiesUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(401)
						res.send(body)
						return
					}
					if (response.status === 404) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.putExtraactivitiesUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(404)
						res.send(body)
						return
					}
					if (response.status === 422) {
						let body: any
						try {
							body = v.modelApiMessageDtoToJson('response', response.body)
						} catch (error) {
							console.error('Invalid response body in extraactivities.putExtraactivitiesUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(422)
						res.send(body)
						return
					}

					console.log('Unsupported response in extraactivities.putExtraactivitiesUpdate', response)
					res.status(500)
					res.send()
				}).catch(function (error) {
					console.error('Unexpected error in extraactivities.putExtraactivitiesUpdate', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.send(error)
			}
		}
	)

}
