/* eslint-disable */
// tslint:disable
/**
 * Appraisal Service
 * Appraisal Service
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

export namespace Api {
	export interface LearningData {
		siNo?: string;
		shortDescription?: string;
		/**
		 * @type {number}
		 * @memberof LearningData
		 */
		apiScore?: number;
	}

	export interface LearningPagedResultData {
		/**
		 * @type {number}
		 * @memberof LearningPagedResultData
		 */
		totalCount?: number;
		items?: Api.LearningData[];
	}

	export interface MessageData {
		message: string;
	}

}
